---
title: "Data viz"
author: "Line Stattau Bisgaard"
date: "17/6/2021"
output: html_document
---

```{r setup}
#load packages
source(here::here("R/package-loading.R"))

#load the tidied dataset (NHANES)
load(here::here("data/nhanes_small.rda"))
```

# One variable plots

```{r continous-variables}
ggplot(nhanes_small, aes(x = bmi)) +
    geom_density()

#geom:"what type of plot"
#aes: short for astetics "

#could also make it as a histogram

ggplot(nhanes_small, aes(x = bmi)) +
    geom_histogram()

```

```{r discrete-variables}
ggplot(nhanes_small, aes(x = sex)) +
    geom_bar()
    
ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()

```

```{r remove-missing-diabetes}

#fjerner alle personer der har na i diabetes variabel
nhanes_tidied <-nhanes_small %>% 
    filter(!is.na(diabetes))

# en anden måde at gøre det på fundet af intsruktør p kurset.
# hedder na_drop og kan brugesi tydiverse. eks nedenfor

nhanes_small %>%
    drop_na(diabetes) %>% 
    ggplot(aes(x= diabetes)) +
    geom_bar()

#gemmer den nye data set i datafolder
usethis::use_data(nhanes_tidied, overwrite = TRUE)

ggplot(nhanes_tidied, aes(x = diabetes)) +
    geom_bar()

```
# 2 vaiables

```{r 2-continuos-variables}

# Using 2 continuous variables
bmi_chol <- ggplot(nhanes_tidied, aes(x = bmi, y = tot_chol))

# Standard scatter plot
bmi_chol + 
    geom_point()
```


```{r 2-continous-variables}
# Standard scatter plot, but with hexagons
bmi_chol + 
    geom_hex()

# Runs a smoothing line with confidence interval
bmi_chol + 
    geom_smooth()

#Or combine two geoms, hex plot with smoothing line
bmi_chol + 
    geom_hex() +
    geom_smooth()
```


```{r 2-discrete-variables}

#fordi vi bruger pipe skalman ikke informere ggplot omhvilket dataset man ønsker at lave ggplot på- det ligger i pipen.

two_discrete <-nhanes_tidied %>% 
    ggplot((aes(x = diabetes, fill = sex)))

two_discrete +
    geom_bar()

two_discrete +
    geom_bar(position = position_dodge())

```

```{r discrete-continous-variables}

two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed +
    geom_boxplot()

#hvis man gerne vil se alle dots

two_mixed +
    geom_jitter()

#måske ikke det bedste når man har så mange datapoints.

two_mixed +
    geom_violin()

```

# plotting three or more variables

```{r using-colour}
# 1 continous and 2 discrete variables
#colour the plot by diabetes status
nhanes_tidied %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes)) +
    geom_boxplot()

# 3 continous variables
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

# 2 discrete and 1 continous variable
# geom_point = scatter plot
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) +
    geom_point()

```
```{r using-faceting}

# figure from before but in new site-by-site layout. So instead
#of plotting both yes and no diabetes in same plot it makes to plots

nhanes_tidied %>% 
    ggplot (aes(x = bmi, y= bp_sys_ave))+
    geom_point() +
    facet_grid(cols = vars(diabetes))

# stack by rows instead of site-by-site
nhanes_tidied %>% 
    ggplot (aes(x = bmi, y= bp_sys_ave))+
    geom_point() +
    facet_grid(rows = vars(diabetes))

# 5 variables
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point() +
    facet_grid(rows = vars(diabetes),
              cols = vars(sex))
    
    
```

#chaning-colours

```{r viridis}
#<- betyder at man "assigner" noget (funktion el data frame) til "noget"

base_barplot <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex)) +
    geom_bar(position = position_dodge())

base_barplot

base_barplot + 
    scale_fill_viridis_d()

# different colours in viridis
base_barplot + 
    scale_fill_viridis_d(option = "A")

# 
base_scatterplot <- nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

base_scatterplot

base_scatterplot + 
    scale_color_viridis_c(option = "H")


#OBS! scale_fill: farvning af rektangel, 
#scale_colour - farvning af dots
```

#Changing plot appearance

```{r build-in-themes}
# Create scatterplot to play with themes
base_scatterplot2 <- base_scatterplot +
    facet_grid(rows = vars(diabetes),
               cols = vars(sex)) +
    scale_color_viridis_c()

# View the plot with the default theme
base_scatterplot2

#try different themes
base_scatterplot2 +
    theme_bw()

base_scatterplot2 +
    theme_minimal()

base_scatterplot2 +
    theme_classic()

# set the theme for all plots
#Helene normally have it in the beginning of project
theme_set(theme_bw())

#change 
base_scatterplot2 +
    labs(title = "BMI, systolic blood pressure, and age,by diabetes and sex", 
         y = "systolic blood pressure (mmHg)", 
         x = "BMI (kg/m2)")

```
# Saving the plot

```{r saving-plots}

ggsave(here::here("doc/images/scatterplot.pdf"), 
       base_scatterplot2, width = 7, height = 5)

```

